image: mcr.microsoft.com/dotnet/sdk:5.0

variables:
  PROJECT_FILE: SimpleTrading.MyNoSqlRepositories

stages:
  - publish-nuget

publish:
  tags: [ monfex ]
  stage: publish
  script:
    - cd ${PROJECT_FOLDER}
    - projectfile=${PROJECT_FILE}
    - ver=$(cat $projectfile.csproj | grep '<Version>' | awk -F ">" '{print $2}' | awk -F"<" '{print $1}')
    - echo $ver
    - dotnet pack $projectfile.csproj --configuration Release --output ./out-nuget
    - dotnet nuget push ./out-nuget/$projectfile.$ver.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
  only:
    - master
