image: mcr.microsoft.com/dotnet/sdk:5.0

variables:
  LIB_FOLDER: SimpleTrading.MyNoSqlRepositories

stages:
  - publish

publish:
  tags: [monfex]
  stage: publish-myservicebus
  script:
    - cd ${LIB_FOLDER}
    - projectfile=${LIB_FOLDER}
    - ver=$(cat $projectfile.csproj | grep '<Version>' | awk -F ">" '{print $2}' | awk -F"<" '{print $1}')
    - echo $ver
    - dotnet pack $projectfile.csproj --include-symbols --include-source --configuration Release --output ./out-nuget
    - dotnet nuget push ./out-nuget/$projectfile.$ver.nupkg --api-key ${NUGET_PUBLISH_KEY} --source https://api.nuget.org/v3/index.json
  only:
    - master
